name: "Tree-sitter fuzzing action"
description: "Fuzzing of tree-sitter grammars using LibFuzzer"
inputs:
  language:
    description: "Name of the language (in your grammar.js)"
    required: true
  external-scanner:
    description: "Path to your external scanner"
  timeout:
    description: "Time to wait if the fuzzer hangs"
    default: 10
  time:
    description: "Fuzzing time"
    default: 120
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.language }}
    - ${{ inputs.timeout }}
    - ${{ inputs.time }}
    - ${{ inputs.external-scanner }}
